version: "3.8"

services:
  nginx-mycrud:
    container_name: nginx-mycrud
    working_dir: /var/www/html/
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/var/www/html
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mycrud-network

  node-mycrud:
    container_name: node-mycrud
    build:
      context: . # Context is the current directory
      dockerfile: Dockerfile # Use the Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - ./backend:/application # Ensure the backend is mounted correctly
      - ./docker-config/node/start_application.sh:/start_application.sh
    restart: always
    entrypoint: ["/bin/sh", "/start_application.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001"]
      interval: 20s
      timeout: 10s
      retries: 3
    networks:
      - mycrud-network

  mysql-mycrud:
    image: mysql:8.0
    container_name: mysql-mycrud
    volumes:
      - db-data:/var/lib/mysql
      - ./docker-config/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf
      - ./docker-config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: "my_crud"
      MYSQL_ROOT_PASSWORD: "mypass"
    networks:
      - mycrud-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-crud
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-mycrud # This should point to the mysql-mycrud service
      PMA_PORT: 3306
      PMA_USER: "root"
      PMA_PASSWORD: "mypass"
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 10000M
    depends_on:
      - mysql-mycrud
    networks:
      - mycrud-network

networks:
  mycrud-network:
    driver: bridge

volumes:
  db-data: {}
